---
title:  "Numpy function"
excerpt: "using in deep-learing"

categories:
  - Useful_Fuction
tags:
  - DL
  - __nditer__  
last_modified_at: 2020-02-16T08:06:00-05:00
---

In [1]:
import numpy as np

In [2]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print(a)
print( 'Modified array is:')
for x in np.nditer(a):
   print(x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [15]:
print("원본 matrix a 의 값")
print(a,"\n","------------------------------------------------")
it = np.nditer(a, flags=['multi_index'], op_flags=['readwrite'])
h = 10
while not it.finished:
    idx = it.multi_index
    tmp_val = a[idx]
    print(idx,"인덱스에 해당하는 원소값들 :\t",tmp_val)
#     print(tmp_val)    
    it.iternext()   

원본 matrix a 의 값
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 
 ------------------------------------------------
(0, 0) 인덱스에 해당하는 원소값들 :	 0
(0, 1) 인덱스에 해당하는 원소값들 :	 5
(0, 2) 인덱스에 해당하는 원소값들 :	 10
(0, 3) 인덱스에 해당하는 원소값들 :	 15
(1, 0) 인덱스에 해당하는 원소값들 :	 20
(1, 1) 인덱스에 해당하는 원소값들 :	 25
(1, 2) 인덱스에 해당하는 원소값들 :	 30
(1, 3) 인덱스에 해당하는 원소값들 :	 35
(2, 0) 인덱스에 해당하는 원소값들 :	 40
(2, 1) 인덱스에 해당하는 원소값들 :	 45
(2, 2) 인덱스에 해당하는 원소값들 :	 50
(2, 3) 인덱스에 해당하는 원소값들 :	 55


#### 위에서 보시다시피, nditer 을 매트릭스 행렬에서, 각 행렬에 해당하는 원소값들을 가져오기 위한 것임